### ISSUE TITLE
Updating the third party

### ISSUE THREAD

**Issue by Misagh90** [dynamic/silverstripe-locator#120]
Hi,
I check the third party folder, and understand that the jQuery Store Locator is changed and the latest version of jQuery Store Locator is 2.7.1
because of this changing the Silverstripe locator needs to update to the new one.

Thanks,

**Comment by muskie9** [comment]
Hi @Misagh90,

Thanks for bringing that up, we've been working internally to decide whether to continue to use the store locator plugin or break away from it and explore something like reactJS to run the mapping. Unfortunately the early version of the locator module uses a hacked store locator script, so updating to the latest plugin version will take some time but we have started that work in a local branch.

Thanks for the feedback and we'll ping this ticket once we determine how we're going to move forward.
