### ISSUE TITLE
Server Error when searching for places which doesn't exist

### ISSUE THREAD

**Issue by michaelwolz** [dynamic/silverstripe-locator#126]
Hey,
I think there is a problem when searching for an address which doesn't exist or at least where the GoogleAPI returns nothing for the request in the DistanceDataExtension. 

It causes the DB Query to have an empty "radians()"  which returns an sql error. 

For example if you put in: "sobiret". I have found very few inputs which throw this error but this one and some others do. 

Thank you

**Comment by muskie9** [comment]
@michaelwolz thanks for reporting this bug. We'll investigate.
