### ISSUE TITLE
Postcode form field

### ISSUE THREAD

**Issue by kabutzel** [dynamic/silverstripe-locator#127]
Hi, i get an error trying to fill a german postcode into the form, where can i change or edit the regex for that?

**Comment by muskie9** [comment]
@kabutzel the postcode field is driven by the [Addressable module](https://github.com/silverstripe-australia/silverstripe-addressable). You should be able to update the regex of the field by calling [`Addressable:: set_postcode_regex('your_regex_here');`](https://github.com/silverstripe-australia/silverstripe-addressable/blob/master/code/Addressable.php#L58-L65) in the `_config.php` of your project. Hope this helps, let us know if you still run into issues! If this resolves your issue feel free to close the ticket.
