### ISSUE TITLE
location can't be unlinked from a page

### ISSUE THREAD

**Issue by guyvanbael** [dynamic/silverstripe-locator#43]
Using the unlink icon results in errors... The only way to unlink it from a page, is to link it to another page.

![schermafbeelding 2014-10-28 om 09 50 44](https://cloud.githubusercontent.com/assets/3098809/4805724/eef94058-5e80-11e4-9a5d-a9de48240311.png)
![schermafbeelding 2014-10-28 om 09 51 00](https://cloud.githubusercontent.com/assets/3098809/4805723/eef8ee50-5e80-11e4-8bb1-a6737b2966c2.png)

**Comment by muskie9** [comment]
@guyvanbael we've discussed our plan for the locator module and unfortunately we'll be reverting some of the recent updates back to the old setup of using a single locator for all locations out of the box. We will however be rolling out some docs/tuts on how you could apply DataExtensions to expand the functionality to support what you're looking for.

In the meantime I'd be happy to help you get the multi-locators setup working. Feel free to email me like you have been or jump on the [SilverStripe IRC channel](http://www.silverstripe.org/community/contributing-to-silverstripe/irc-channel/) as I'm usually on there daily.

I'll try to keep a branch with the current state of the module so patches could be applied to the current setup and in case you're pulling this module in via composer or git.

**Comment by muskie9** [comment]
Re-opening. I'll work on a fix for this with the current setup so this branch is in working order.

**Comment by jsirish** [comment]
is this still an issue? I think all of this code has been removed from the repo in favor of #67

**Comment by jsirish** [comment]
closing - no longer a many_many between Locator and Location
