### ISSUE TITLE
The "Postal Code" field only accepts Zip codes. 

### ISSUE THREAD

**Issue by Dale-WAX** [dynamic/silverstripe-locator#98]
The Postal Code Field will only accept numbers like a zip code. When entering a letter, like in a Postal Code, the validation errors out. 

90210 = OK / T3E 2H6 = Error

**Comment by muskie9** [comment]
Hi @Dale-WAX, thanks for pointing this out. The Postal Code regex is actually set in the [silverstripe-australia/silverstripe-addressable module](https://github.com/silverstripe-australia/silverstripe-addressable/blob/master/code/Addressable.php#L14), however, you should be able to set a custom regex via your `_config/config.yml` file [per their config checking here](https://github.com/silverstripe-australia/silverstripe-addressable/blob/master/code/Addressable.php#L70). Your config might look something like:

```yml
Addressable:
  set_postcode_regex: 'your_regex_here'
```

Alternatively, you should be able to do the followingin your `_config.php`: `Config::inst()->update('Addressable', 'set_postcode_regex', 'your_regex_here');`.

**Comment by Dale-WAX** [comment]
Thanks for the advice, @muskie9. I tried a few ways as you suggested, but honestly it's over my head. I'm going to do some googling tomorrow based off of your advice.

**Comment by Dale-WAX** [comment]
Slept on it and got it working. Thanks again.
